### ISSUE TITLE
webpackConfig isn't being used in the karma.conf.js config

### ISSUE THREAD

**Issue by nerdkid93** [nnupoor/webpack4vue#2]
On [this line](https://github.com/nnupoor/webpack4vue/blob/master/karma.conf.js#L41), you `require` the `webpack.config.js` file, but you have already done so earlier in the script.

**Comment by nnupoor-zz** [comment]
I'll fix this once I am free. Thanks for pointing out. 🍺

**Comment by nnupoor-zz** [comment]
Fixed the issue. reusing the variable now.
